version: '3.9'

services:
  mongo-rs0-1:
    image: mongo
    build: ./mongo-rs0-1
    command: --replSet rs0 --oplogSize 128
    ports:
      - "27040:27017"
    volumes:
      - ./mongo-rs0-1/data:/data/db
    networks:
      - mongo-network

  mongo-rs0-2:
    image: mongo
    command: --replSet rs0 --oplogSize 128
    ports:
      - "27041:27017"
    volumes:
      - ./mongo-rs0-2/data:/data/db
    networks:
      - mongo-network

  mongo-rs0-3:
    image: mongo
    command: --replSet rs0 --oplogSize 128
    ports:
      - "27042:27017"
    volumes:
      - ./mongo-rs0-3/data:/data/db
    networks:
      - mongo-network

  setup-rs:
    image: setup-rs
    build: ./setup
    depends_on:
      - mongo-rs0-1
      - mongo-rs0-2
      - mongo-rs0-3
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongo-rs0-1
    networks:
      - mongo-network

  nginx:
    image: nginx:latest
    container_name: nodejs-rest-api-nginx
    ports:
      - "8080:80"
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
